### ISSUE TITLE
GitHub vs GitLab

### ISSUE THREAD

**Issue by anupamsr** [deuiore/palemoon-overlay#10]
Hi!

[Opened a similar issue at GitLab https://gitlab.com/deu/palemoon-overlay/issues/2 ]

Layman refers to GitLab version, while development seems to be happening at GitHub. Any chance of getting these two synced, or getting layman updated to the GitHub version?

**Comment by deuiore** [comment]
You mean with "layman -i", right? Yeah, that's weird. I solved it by re-emerging layman. No idea why that worked.

Could you try doing the same and telling me if that works for you too?

In the meanwhile I really should add some pointers to this repository in the old GitLab one.

**Comment by anupamsr** [comment]
No. I meant "layman -a". I re-emerged layman as well as did layman -S etc, but it still pulls the repo from gitlab instead of github.

**Comment by deuiore** [comment]
That's weird. Do you perchance still have the old `/etc/layman/overlays/palemoon.xml` around?

**Comment by anupamsr** [comment]
You were right. That file remains even after deleting palemoon repo. I followed following steps and it resolved the issue:

1. `laymen -d palemoon`
2. `rm /etc/layman/overlays/palemoon.xml`
3. `layman -L`
4. `layman -a palemoon`
