### ISSUE TITLE
Palemon could get x86 keyword

### ISSUE THREAD

**Issue by hkmaly** [deuiore/palemoon-overlay#11]
I think that you should add ~x86 keyword to palemoon. It does compile on x86 (in fact, there are "if x86" in the ebuild).

**Comment by deuiore** [comment]
Yes, you are right. The problem was that I never had the occasion to actually test them on a x86 environment, so I left the keyword out. You said it does compile. I'll trust your word and add it for now and if nobody complains we'll keep it.

**Comment by hkmaly** [comment]
Note that while Palemoon 26.2 still compiles and work, the video support doesn't seem to.
