### ISSUE TITLE
Sound Issues

### ISSUE THREAD

**Issue by JStyle21** [deuiore/palemoon-overlay#13]
HI,

I've installed palemoon from the overlay and i'm having some sound issues.

Any idea why would it output the sound to s/pdif 1 (HDMI) instead of my main soundcard?
Or where can i change or control that? it complies with alsa but i didn't find anything in alsa or pusleaudio or palemoon settings to help me change that.

**Comment by deuiore** [comment]
I don't have this problem with any of the ebuilds, and you gave too little information to hazard any guess.

Do you have this problem only with Pale Moon? What about other GTK+ applications?

You should try emerging the latest `palemoon-bin`, and if the problem persists ask for support in the [official forums](http://forum.palemoon.org/), or if you are confident it's a Pale Moon bug, submit an issue to [their bug tracker](https://github.com/MoonchildProductions/Pale-Moon/issues), in any case providing all the necessary information.

**Comment by JStyle21** [comment]
I actually took www-client/palemoon-25.7.1::palemoon not palemoon-bin so i'm not 100% if that makes any difference but the issue is based on my system's set up so it's possible that some applications can get this wrong but the question is where do i change that? it's not a palemoon bug and i don't see it in other applications and if i do like firefox or vlc i can change the sound output with the mixer. for some reason the mixer doesn't see palemoon at all so i don't know how to fix this.

**Comment by JStyle21** [comment]
Ok quick addition on this.

I'm using KDE and i want Kmix to recognize Palemoon, then i can control it and defer it to any sound device i want.

I'm only seeing Firefox there:
http://s15.postimg.org/7voedfpxn/snapshot2.png

**Comment by deuiore** [comment]
Again, you should try the `palemoon-bin` ebuild to be sure that the problem isn't with how the package is built by portage but with Pale Moon itself. Then report back.

In the former case I could try to figure out what the problem is. In the latter case, the problem would be with Pale Moon itself and how it behaves in your particular setup (of which you still have to provide detailed information), so you should report it in the places I mentioned in my previous comment.

**Comment by JStyle21** [comment]
Ok Dude, i've tried palemoon-bin and the issue is still there...
I will report to Palemoon bug tracker or forums.

Thanks for your help.
If you need anything let me know.
