### ISSUE TITLE
build with system webp library fails

### ISSUE THREAD

**Issue by plusInfinity** [deuiore/palemoon-overlay#21]
Hi guys,

I compile palemoon with system-libs use-flag. In all 26 versions I have to delete system-webp from mozconfig_with section in ebuild since otherwise compilation fails. I have this problem with both 0.4.0 and 0.4.2 vesions of libwebp from portage. 

Could you delete system-webp from mozconfig_with section if I'm not the only one who has this problem?

**Comment by deuiore** [comment]
I just emerged palemoon-26.2.0 with USE=system-libs and it all went well for me (libwebp-0.4.2).
What other USE flags are you using with Pale Moon? What about libWebP?

**Comment by plusInfinity** [comment]
Ups.. It looks like palemoon-26.2.0 compiles for me as well after reemerging libwebp-0.4.2. Can't reproduce it now even with older palemoon-26.1.1-r1 and  palemoon-26.1.0 where I had the issue. Sorry for bothering, please close the bug.

**Comment by plusInfinity** [comment]
And thank you for your help!

**Comment by deuiore** [comment]
No problem. I'm glad it works!
