### ISSUE TITLE
Video support in Palemoon 26.2 crashes on x86

### ISSUE THREAD

**Issue by hkmaly** [deuiore/palemoon-overlay#22]
The gstreamer 1 based video support consistently crash for me whenever I'll try any video in Palemoon. Reported upstream as https://github.com/MoonchildProductions/Pale-Moon/issues/418 (look in that bug for details).

Looking for anyone using Palemoon on x86 gentoo to either confirm the problem or try to post how his/her configuration differs from mine.

**Comment by hkmaly** [comment]
Note: gstreamer can be turned off in about:config, so it's not critical error.

**Comment by deuiore** [comment]
That doesn't seem to be an ebuild-related bug.
What I could do is disable the gstreamer support for the x86 build, or mask x86 again. Unless you or some other x86 user manages to find out what the real problem is.
[As you might remember](https://github.com/deuiore/palemoon-overlay/issues/11), x86 used to be masked because I don't have the time to stay behind it, since I don't use Pale Moon on any x86 system.

**Comment by hkmaly** [comment]
Can you link to this bug from ebuild or something? It works on Ubuntu and CentOS ; I still hope it works for someone else on Gentoo as well and that I will be able to make it work based on differences in our systems. But so far it seems I'm only one using Pale Moon on Gentoo on x86, which means no harm leaving it as-is :-)

**Comment by deuiore** [comment]
Could you confirm this happening with the palemoon-27.1.0 ebuild as well?
Pale Moon should now use FFmpeg for video decoding, so this being a bug caused by GStreamer it shouldn't happen any more.

**Comment by hkmaly** [comment]
I would like to try, but when I tried to compile it I got following on installation:
```
>>> Install palemoon-27.1.0 into /var/tmp/portage/www-client/palemoon-27.1.0/image/ category www-client
...
 0:19.00 Executing /var/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/obj-i686-pc-linux-gnu/dist/bin/xpcshell -g /var/tmp/portage/www-client
/palemoon-27.1.0/work/palemoon-27.1.0/obj-i686-pc-linux-gnu/dist/bin/ -a /var/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/obj-i686-pc-linu
x-gnu/dist/bin/ -f /var/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/toolkit/mozapps/installer/precompile_cache.js -e precompile_startupcac
he("resource://gre/");
 0:19.45 /var/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/obj-i686-pc-linux-gnu/dist/bin/xpcshell: /usr/lib/palemoon/libxul.so: version `x
ul3' not found (required by /var/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/obj-i686-pc-linux-gnu/dist/bin/xpcshell)
 0:19.46 Traceback (most recent call last):
 0:19.46   File "/var/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/toolkit/mozapps/installer/packager.py", line 404, in <module>
 0:19.46     main()
 0:19.46   File "/var/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/toolkit/mozapps/installer/packager.py", line 398, in main
 0:19.46     args.source, gre_path, base)
 0:19.46   File "/var/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/toolkit/mozapps/installer/packager.py", line 156, in precompile_cache
 0:19.46     errors.fatal('Error while running startup cache precompilation')
 0:19.46   File "/var/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/python/mozbuild/mozpack/errors.py", line 101, in fatal
 0:19.46     self._handle(self.FATAL, msg)
 0:19.46   File "/var/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/python/mozbuild/mozpack/errors.py", line 96, in _handle
 0:19.46     raise ErrorMessage(msg)
 0:19.46 mozpack.errors.ErrorMessage: Error: Error while running startup cache precompilation
```
... apparently, it's trying to use library from old palemoon for installing new one or something like this.

**Comment by hkmaly** [comment]
After I removed /usr/lib/palemoon, I managed to install palemoon 27.3.0 and can confirm it doesn't crash on that "reproducible crash" page anymore. Meanwhile, I filled the "can't install palemoon 27 if palemoon 26 is installed" as #48
