### ISSUE TITLE
Please add RESTRICT=mirror

### ISSUE THREAD

**Issue by vaeth** [deuiore/palemoon-overlay#25]
It would help and restrict traffic to gentoo mirrors if you add the line
```
RESTRICT="mirror"
 ```

to the ebuild (in the main scope): Although this line would have to be removed if palemoon goes into the main gentoo repository, it prevents that portage looks for palemoon in the list of all configured gentoo mirrors (none of which contains palemoon yet, of ocurse) before finally it downloads from the actual source.

I do this with all ebuilds in the mv overlay for which the sources are not available on gentoo mirrors.

**Comment by deuiore** [comment]
From what I gathered from some Gentoo developers, that is somehow not desirable, since I guess one could very well have some third party mirror set up that does in fact contain the package.
If there were a way to prioritise them, having the SRC_URI one take precedence, I would like that too, but I don't know of any way to do that (if it's even possible).

**Comment by vaeth** [comment]
"mirror" (in RESTRICT="mirror") does not refer to a third-party mirror but to the official gentoo mirrors which are set up with GENTOO_MIRRORS. As that name suggests, their content is all cloned from a master mirror which in turn is determined through a script from the content of the files in the main gentoo repository. Since palemoon does not belong to that repository, the official gentoo mirrors will never carry that package (even if you should volunteer to provide a new gentoo mirror following the official rules).
Of course, you might set up an independent gentoo mirror not following official rule (i.e. forcing palemoon in the directory even if the master mirror does not contain it) and recommend users to put this first in GENTOO_MIRRORS, but this would mean that all users doing this would first try for _every_ gentoo package to fetch it from your mirror; users not following this recommendation would still ask the other GENTOO_MIRRORS in advance.

The way to set up a mirror for palemoon - as long as it is not in the official gentoo tree - is to put RESTRICT=mirror in the ebuild and to specify the mirror address of the file first in the SRC_URI:

> If there were a way to prioritise them, having the SRC_URI one take precedence

The precedence is the order in which they are listed in SRC_URI: The second is only used as a fallback (if the first failed), etc.
