### ISSUE TITLE
Palemoon fails to build because Gentoo mirrors do not carry Palemoon sources

### ISSUE THREAD

**Issue by grepwood** [deuiore/palemoon-overlay#3]
The ebuild should fetch the source code from `ftp://source:current@ftp.palemoon.org/` rather than from the mirrors specified in `/etc/portage/make.conf`

**Comment by grepwood** [comment]
Nevermind. This is due to not setting up a FTP proxy in my env.

**Comment by vaeth** [comment]
It would help to set <code>RESTRICT="mirror"</code> in the ebuild: Then emerge would not try the gentoo mirrors, first
