### ISSUE TITLE
Version 27.1.0

### ISSUE THREAD

**Issue by Ch197007h** [deuiore/palemoon-overlay#35]
Great work with the overlay, and just letting you know that v27.1.0 is now available.

**Comment by Massimo-B** [comment]
Yes, please bump the version as there are many security changes:
https://www.palemoon.org/releasenotes.shtml

And by the way consider porting palemoon to portage.

**Comment by deuiore** [comment]
The ebuild for 27.1.0 is now out.

@Massimo-B That would mean filling bug forms and a much slower approval process, possibly for each version, considering that I'm not a Gentoo Developer. Given the current state of the palemoon-27 source ebuilds (the resulting build is unstable when built with gcc-5, Gentoo's main compiler) that would probably also mean submitting patches to make Pale Moon gcc-5 ready. Regrettably that's not something I have the time for right now.
