### ISSUE TITLE
build fails with gcc-4.9.4

### ISSUE THREAD

**Issue by thunderrd** [deuiore/palemoon-overlay#38]
With 26.5.0 already installed, unmasking v27.1.0 fails with gcc-4.9.4 enabled.
This is the end of the build log:

`
 0:15.00 js/src> checking for posix_fallocate... (cached) yes
 0:15.00 js/src> checking for malloc.h... (cached) yes
 0:15.00 js/src> checking for setlocale... yes
 0:15.00 js/src> checking for localeconv... (cached) yes
 0:15.00 js/src> checking for malloc_size... no
 0:15.00 js/src> checking for malloc_usable_size... (cached) yes
 0:15.00 js/src> updating cache /mnt/ext4_STORAGE/var/tmp/notmpfs/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/obj-x86_64-unknown-linux-gnu/config.cache
 0:15.00 js/src> creating ./config.status
 0:15.00 js/src> /bin/sh: ./config.status: /mnt/ext4_STORAGE/var/tmp/notmpfs/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/obj-x86_64-unknown-linux-gnu/_virtu: bad interpreter: No such file or directory
 0:18.36 *** Fix above errors and then restart with\
 0:18.36                "/usr/bin/gmake -f client.mk build"
 0:18.36 gmake: *** [client.mk:363: configure] Error 1
 * ERROR: www-client/palemoon-27.1.0::palemoon failed (configure phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 115:  Called src_configure
 *   environment, line 3866:  Called die
 * The specific snippet of code:
 *       python2 mach configure || die
 * 
 * If you need support, post the output of `emerge --info '=www-client/palemoon-27.1.0::palemoon'`,
 * the complete build log and the output of `emerge -pqv '=www-client/palemoon-27.1.0::palemoon'`.
 * The complete build log is located at '/mnt/ext4_STORAGE/var/tmp/notmpfs/portage/www-client/palemoon-27.1.0/temp/build.log'.
 * The ebuild environment file is located at '/mnt/ext4_STORAGE/var/tmp/notmpfs/portage/www-client/palemoon-27.1.0/temp/environment'.
 * Working directory: '/mnt/ext4_STORAGE/var/tmp/notmpfs/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0'
 * S: '/mnt/ext4_STORAGE/var/tmp/notmpfs/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0'
`

Build environment:
`root@Q6600: ~# emerge --info
Portage 2.3.4 (python 3.5.3-final-0, default/linux/amd64/13.0/desktop, gcc-4.9.4, glibc-2.24-r1, 4.10.1-ck x86_64)
=================================================================
System uname: Linux-4.10.1-ck-x86_64-Intel-R-_Core-TM-2_Extreme_CPU_X9650_@_3.00GHz-with-gentoo-2.3
KiB Mem:     8168968 total,   3655080 free
KiB Swap:    1060860 total,   1060860 free
Timestamp of repository gentoo: Fri, 10 Mar 2017 06:00:01 +0000
sh bash 4.4_p12
ld GNU ld (Gentoo 2.27 p1.0) 2.27
app-shells/bash:          4.4_p12::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.24.1-r1::gentoo
dev-lang/python:          2.7.13::gentoo, 3.4.6::gentoo, 3.5.3::gentoo
dev-util/cmake:           3.7.2::gentoo
dev-util/pkgconfig:       0.29.1::gentoo
sys-apps/baselayout:      2.3::gentoo
sys-apps/openrc:          0.23.2::gentoo
sys-apps/sandbox:         2.10-r3::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r2::gentoo
sys-devel/automake:       1.15-r2::gentoo
sys-devel/binutils:       2.27::gentoo
sys-devel/gcc:            4.9.4::gentoo, 5.4.0-r3::gentoo
sys-devel/gcc-config:     1.8-r1::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1::gentoo
sys-kernel/linux-headers: 4.10::gentoo (virtual/os-headers)
sys-libs/glibc:           2.24-r1::gentoo
Repositories:

gentoo
    location: /mnt/ext4_STORAGE/usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-extra-opts: --verbose --progress --exclude-from=/etc/portage/rsync_excludes

hnaparst
    location: /mnt/ext4_STORAGE/var/lib/layman/hnaparst
    sync-type: laymansync
    sync-uri: https://github.com/hnaparst/overlay.git
    masters: gentoo
    priority: 50

palemoon
    location: /mnt/ext4_STORAGE/var/lib/layman/palemoon
    sync-type: laymansync
    sync-uri: https://github.com/deuiore/palemoon-overlay.git
    masters: gentoo
    priority: 50

sabayon
    location: /mnt/ext4_STORAGE/var/lib/layman/sabayon
    sync-type: laymansync
    sync-uri: git://github.com/Sabayon/for-gentoo.git
    masters: gentoo
    priority: 50

torbrowser
    location: /mnt/ext4_STORAGE/var/lib/layman/torbrowser
    sync-type: laymansync
    sync-uri: git://github.com/MeisterP/torbrowser-overlay.git
    masters: gentoo
    priority: 50

vaca
    location: /mnt/ext4_STORAGE/var/lib/layman/vaca
    sync-type: laymansync
    sync-uri: git://github.com/hashashin/gentoo-vaca-overlay.git
    masters: gentoo
    priority: 50

BZ-overlay
    location: /mnt/ext4_STORAGE/usr/local/portage
    masters: gentoo
    priority: 60

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt /usr/share/themes/oxygen-gtk/gtk-2.0"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/mnt/ext4_STORAGE/usr/portage/distfiles"
EMERGE_DEFAULT_OPTS="--quiet-build=n"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://gentoo.mirrors.easynews.com/linux/gentoo/ http://ftp.lecl.net/pub/gentoo/"
LANG="en_US.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j4"
PKGDIR="/mnt/ext4_STORAGE/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_EXTRA_OPTS="--verbose --progress --exclude-from=/etc/portage/rsync_excludes"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 branding bzip2 cairo cdda cdr cli consolekit cracklib crypt cxx dbus device-mapper directfb dri dts dvd dvdr emboss encode exif fam ffmpeg firefox flac fortran gdbm gif glamor gpm gtk iconv infinality ipv6 jack jpeg lcms ldap libnotify mad mmx mng modules mp3 mp4 mpeg multilib ncurses nls nptl offensive ogg opengl openmp openssl pam pango pcre pdf png policykit ppds python qt5 readline samba sdl seccomp session spell sse sse2 ssh ssl startup-notification svg tcpd threads tiff truetype udev udisks unicode usb uuid vdpau vorbis wxwidgets x264 xattr xcb xcomposite xft xml xv xvid zlib" ABI_X86="32 64" ALSA_CARDS="ca0106" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2 sse3 sse4_1 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4 python3_5" RUBY_TARGETS="ruby21" USERLAND="GNU" VIDEO_CARDS="nvidia" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, USE_PYTHON
`

**Comment by thunderrd** [comment]
This issue persists with the new 27.1.2 version, available today.  The error output is identical.

**Comment by mattatobin** [comment]
Why is this calling mach configure.. You aren't supposed to do that.

**Comment by thunderrd** [comment]
I can't explain what the ebuild is doing.  I simply emerge it and this is what is happening.

Is there something in the use flags that is set wrong?

**Comment by thunderrd** [comment]
Full build log here:
[build.log.txt](https://github.com/deuiore/palemoon-overlay/files/837331/build.log.txt)

**Comment by Massimo-B** [comment]
Same here, any news? As mv said in #40 building with gcc-5 works fine if setting some patched --disable-system-cairo. Wouldn't that be the way to get the current sources built?

**Comment by thunderrd** [comment]
I've talked to both deu and mattatobin on IRC; they ack the issue and have told me the solution is in the pipe, but perhaps not as soon as you'd like.

Anyhow, it will be worked out eventually.

**Comment by Kalle72** [comment]
Same problem here. 

@ massimo-b: At my machine palemoon claims that gcc-5 is not recommended to build it and thereby the build-process stops. How do you make it work with gcc-5

Best regards 
Kalle

**Comment by nado** [comment]
Same issue as https://github.com/deuiore/palemoon-overlay/issues/37, this could be closed as duplicate.
My PR https://github.com/deuiore/palemoon-overlay/pull/54 tries to address that issue, could you try to see if the fix is enough for you ?

**Comment by deuiore** [comment]
#54 has been merged. Could you check if the build succeeds now?

**Comment by thunderrd** [comment]
Closing in light of #54 and successful build with gcc-4.9.4
