### ISSUE TITLE
Why are devtools not compiled?

### ISSUE THREAD

**Issue by Nebula-Mechanica** [deuiore/palemoon-overlay#41]
Devtools are back since 27.0.2. I have them in Palemoon under Windows. Why are they not in when built from this overlay?

**Comment by deuiore** [comment]
Good point. Interestingly they aren't enabled by default in the configure, although all the binaries ship with them built-in.
I will add an USE flag (enabled by default) and release a r1 ebuild for 27.2.1 in a short while.
