### ISSUE TITLE
palemoon doesn't compile with hunspell-1.6.1-r1

### ISSUE THREAD

**Issue by plusInfinity** [deuiore/palemoon-overlay#42]
looks like it's supported only in firefox-55 and most likely not in palemoon yet.
https://bugzilla.mozilla.org/show_bug.cgi?id=1350908
please make dependence on hunspell-1.6.0 if I'm right.

**Comment by plusInfinity** [comment]
Hi again, in the end I was able to build it with 1.6.1-r1 but only with gcc-5.4.0-r3. Arch developers suggest that gcc-5 is stable with palemoon, see: https://aur.archlinux.org/packages/palemoon/

**Comment by deuiore** [comment]
Thing is, it's really not: I still experience random crashes when building with it.

**Comment by plusInfinity** [comment]
Hm.., for me it worked out fine. The only thing which I could suggest is try to build palemoon with binutils-2.25.
