### ISSUE TITLE
palemoon-bin's SRC_URI is broken.

### ISSUE THREAD

**Issue by crocket** [deuiore/palemoon-overlay#43]
The URI needs to be updated.

**Comment by deuiore** [comment]
The Pale Moon servers went down some days ago and still haven't come back up fully, especially the Linux parts.
See: https://forum.palemoon.org/viewtopic.php?t=15383&p=111320#p111320

In the meanwhile you can download the binary from https://linux.palemoon.org/ and put it in your `/usr/portage/distfiles/`, then you should be able to correctly emerge the package.
