### ISSUE TITLE
Can't emerge without sound (no ALSA or PulseAudio installed)

### ISSUE THREAD

**Issue by Zekario** [deuiore/palemoon-overlay#50]
I'm trying to emerge Pale Moon with this overlay on a soundless system, but it fails because it requires either ALSA or PulseAudio. How can I do this?

**Comment by deuiore** [comment]
I upgraded the 27.4.2 ebuild to allow emerging it without specifying either USE flag.
Could you please test it and report any issues?

**Comment by Zekario** [comment]
It appears to allow it now.
