### ISSUE TITLE
update dependency hunspell for new version

### ISSUE THREAD

**Issue by hoehnp** [deuiore/palemoon-overlay#51]
In the gentoo repos, hunspell does not exit anymore in version 1.6.0, as specified in the ebuild file of palemoon. Could you please try to update the ebuild accordingly?

**Comment by deuiore** [comment]
Unfortunately at this point 1.6.0 is the only version supported by Pale Moon. See #42.
Trying to build Pale Moon with a newer version results in a build failure.
I suggest you disable the `system-hunspell` USE flag for now.
