### ISSUE TITLE
ffmpeg is a dependency

### ISSUE THREAD

**Issue by BetaRays** [deuiore/palemoon-overlay#58]
Pale moon can use ffmpeg if it exists, but unlike firefox, it is not strictly required.

**Comment by BetaRays** [comment]
I meant that even for the binaries, it's optional at runtime.

**Comment by deuiore** [comment]
I'm not sure I want to do that.
The binary package is compiled with `MOZ_FFMPEG=1` and the preference `media.ffmpeg.enabled` is set to `true` by default.
So even if it does still work with no obvious errors or crashes without ffmpeg, I don't believe we should assume it's as intended.

**Comment by BetaRays** [comment]
Maybe I just thought it was intended because I got a binary from the website and installed missing libraries when it didn't start, but for now it didn't crash, websites can even see that audio and video support isn't present.
But maybe you're right, I guess the best way to know it is asking if it's intended or not.
