### ISSUE TITLE
Ebuild for palemoon-bin required

### ISSUE THREAD

**Issue by anupamsr** [deuiore/palemoon-overlay#7]
Hi!

Could you please add ebuild for binary version of palemoon? I have created and tested them for some time and they seem to work too. If you want you can use them

**Comment by deuiore** [comment]
Oh, that's nice!
Do you think you could submit a pull request?

**Comment by anupamsr** [comment]
Thanks. I found one problem with the ebuild - I don't know how to inject *.js (about:config) files. That is where I am stuck. I will submit a pull request, though, right now.
